### ISSUE TITLE
Getting "invalid-token" from local Keycloak

### ISSUE THREAD

**Issue by jxsl13** [lucabaggi/keycloak-token-exchange#1]
Hey, I have been trying to use your docker image, sadly I do get this error when trying to exchange the externally issued token:

```
{
    "error": "invalid_token",
    "error_description": "invalid token"
}
```

Step 1 would be to fetch the user token, which is: 
```
{
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwVHFxY3k0dnRTMkJ3LUY5WjRGT21VWEpDRzlaaWlGdVdJSnI0ekRrWGcwIn0.eyJqdGkiOiI2NjMyMjNjZC01NWE5LTRhNTItODUwNi02MTU1OTFiNDU5ZmUiLCJleHAiOjE2MTQ3ODQ1MzMsIm5iZiI6MCwiaWF0IjoxNjE0Nzg0MjMzLCJpc3MiOiJodHRwczovLzlmMjc4NTY5ZWE0ZS5uZ3Jvay5pby9hdXRoL3JlYWxtcy9CYW5rIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjY5NDJiZmE1LWU4YjYtNDM5NC1iNWJjLTkyYTJmMWM3MjlmNiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImJhbmstb3BlbmlkLWNvbm5lY3QtbG9naW4iLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiIzN2Y1ZThmNy03NzMxLTQxYmUtODdiYy1mNDg1ZDVkMGY1ZDAiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJNYXJpbyBSb3NzaSIsInByZWZlcnJlZF91c2VybmFtZSI6Im1hcmlvLnJvc3NpIiwiZ2l2ZW5fbmFtZSI6Ik1hcmlvIiwiZmFtaWx5X25hbWUiOiJSb3NzaSIsImVtYWlsIjoibWFyaW8ucm9zc2lAZW1haWwuY29tIn0.Zfj9yziXpiKgElRZW6y01Qz4QirGzy_eUA64elkmdA8gfAkzZoWprgOQqTaMUwiCTSdC3r99592dRD4NhVSo9ZbtealFnZ2WwE0JvsGFYwQlRLq9KiqLPx2xjf8PtqMDObanfcmODq3jtEP_Hmnj4LwXMJMaykXYWD9yhZykmf5aZFXfDY1ET0vUoj-V39Vs3ofX9WLu_NUNzYe5VjEM3T39guGw3xWAg2PkykELsD2IXd0Lilch8abgSfjfTiLzWBryXbteYrkDXHSrC-GvE-OgWlB9bJVh4YI5WSrOoQkD_bX8Bnr38t9JBRA4Wj6xbCiI32IBhwwqhfQblzdZtg",
    "expires_in": 300,
    "refresh_expires_in": 1800,
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkN2YyMDhlNy0xNjAwLTQzYzktOWUyYi0wNmY0Yzk5ZTUxZDUifQ.eyJqdGkiOiI1YjdlNGE2Ni0yZDY1LTRiYjEtYmYyYS03NzkzMGQyN2NlODYiLCJleHAiOjE2MTQ3ODYwMzMsIm5iZiI6MCwiaWF0IjoxNjE0Nzg0MjMzLCJpc3MiOiJodHRwczovLzlmMjc4NTY5ZWE0ZS5uZ3Jvay5pby9hdXRoL3JlYWxtcy9CYW5rIiwiYXVkIjoiaHR0cHM6Ly85ZjI3ODU2OWVhNGUubmdyb2suaW8vYXV0aC9yZWFsbXMvQmFuayIsInN1YiI6IjY5NDJiZmE1LWU4YjYtNDM5NC1iNWJjLTkyYTJmMWM3MjlmNiIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJiYW5rLW9wZW5pZC1jb25uZWN0LWxvZ2luIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiMzdmNWU4ZjctNzczMS00MWJlLTg3YmMtZjQ4NWQ1ZDBmNWQwIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUifQ.WSjClrrVEYq4elQ9iilbGIQBbv5BtnTGovwv1XkQ-TU",
    "token_type": "bearer",
    "not-before-policy": 0,
    "session_state": "37f5e8f7-7731-41be-87bc-f485d5d0f5d0",
    "scope": "email profile"
}
```

plain text JWT token data part (`access_token`):

```
{
  "jti": "663223cd-55a9-4a52-8506-615591b459fe",
  "exp": 1614784533,
  "nbf": 0,
  "iat": 1614784233,
  "iss": "https://9f278569ea4e.ngrok.io/auth/realms/Bank",
  "aud": "account",
  "sub": "6942bfa5-e8b6-4394-b5bc-92a2f1c729f6",
  "typ": "Bearer",
  "azp": "bank-openid-connect-login",
  "auth_time": 0,
  "session_state": "37f5e8f7-7731-41be-87bc-f485d5d0f5d0",
  "acr": "1",
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "email_verified": false,
  "name": "Mario Rossi",
  "preferred_username": "mario.rossi",
  "given_name": "Mario",
  "family_name": "Rossi",
  "email": "mario.rossi@email.com"
}
```

Step two was to check the token at the external IDP's userinfo endpoint: 
```
{
    "sub": "6942bfa5-e8b6-4394-b5bc-92a2f1c729f6",
    "email_verified": false,
    "name": "Mario Rossi",
    "preferred_username": "mario.rossi",
    "given_name": "Mario",
    "family_name": "Rossi",
    "email": "mario.rossi@email.com"
}
```
The URL `https://9f278569ea4e.ngrok.io``has also been changed in the internal keycloak that connects to the "oidc" external identity provider.
So in theory your provided Postman request for exchanging the token should work, but I really don't know why, but it does not do what should be expected.

```
{
    "error": "invalid_token",
    "error_description": "invalid token"
}
```

Exposing the external identity provider via ngrok works (with some ssl certificate errors, but that should not be the problem, I hope)

I would be glad if you could give me some pointers in this regard.

Best regards.

**Comment by tl-luca-baggi** [comment]
Hey @jxsl13 ,
can you please double check that the `oidc` identity provider inside `keycloak` has been updated with the correct ngrok base URL? 
In particular the most important one is `User Info URL` that must have the following value: `<your-ngrok-url>/auth/realms/Bank/protocol/openid-connect/userinfo`

What happens under the hood when you invoke the token exchange is the following:
- `keycloak` calls the configured `oidc` user info endpoint (which is the `external_idp` endpoint)
- it then stores the user info received in its own database (if is not already present), and returns an access token valid for the created user

This means that usually an `invalid_token` error is related to the fact that `keycloak` is getting an error trying to access the `external_idp` user info endpoint.

If all the configuration above are correct but you still getting the error, let's proceed in this way:
1. check if there's any useful docker log 
2. if not (as I suspect) try to enhance log level on `keycloak` and `external_idp`: open the `docker-compose.yml` file and uncomment for both services the following env variables:
```
#KEYCLOAK_LOGLEVEL: DEBUG
#ROOT_LOGLEVEL: DEBUG
```

Doing this hopefully you should be able to get more information about the error

**Comment by lucabaggi** [comment]
Hey @jxsl13 ,
can you please double check that the `oidc` identity provider inside `keycloak` has been updated with the correct ngrok base URL? 
In particular the most important one is `User Info URL` that must have the following value: `<your-ngrok-url>/auth/realms/Bank/protocol/openid-connect/userinfo`

What happens under the hood when you invoke the token exchange is the following:
- `keycloak` calls the configured `oidc` user info endpoint (which is the `external_idp` endpoint)
- it then stores the user info received in its own database (if is not already present), and returns an access token valid for the created user

This means that usually an `invalid_token` error is related to the fact that `keycloak` is getting an error trying to access the `external_idp` user info endpoint.

If all the configuration above are correct but you still getting the error, let's proceed in this way:
1. check if there's any useful docker log 
2. if not (as I suspect) try to enhance log level on `keycloak` and `external_idp`: open the `docker-compose.yml` file and uncomment for both services the following env variables:
```
#KEYCLOAK_LOGLEVEL: DEBUG
#ROOT_LOGLEVEL: DEBUG
```

Doing this hopefully you should be able to get more information about the error

**Comment by jxsl13** [comment]
```
17:34:56,438 DEBUG [org.apache.http.conn.ssl.SSLConnectionSocketFactory] (default task-11) Starting handshake
17:34:56,527 DEBUG [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] (default task-11) http-outgoing-3: Shutdown connection
17:34:56,528 DEBUG [org.apache.http.impl.execchain.MainClientExec] (default task-11) Connection discarded
17:34:56,528 DEBUG [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] (default task-11) Connection released: [id: 3][route: {s}->https://3bbf16f2b3d8.ngrok.io:443][total kept alive: 0; route allocated: 0 of 64; total allocated: 0 of 128]
17:34:56,532 DEBUG [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-11) Failed to invoke user info for external exchange: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.apache.httpcomponents.core//org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
        at org.apache.httpcomponents.core//org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
        at org.apache.httpcomponents.core//org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.httpcomponents.core//org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.httpcomponents.core//org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.keycloak.keycloak-server-spi-private@7.0.1//org.keycloak.broker.provider.util.SimpleHttp.makeRequest(SimpleHttp.java:215)
        at org.keycloak.keycloak-server-spi-private@7.0.1//org.keycloak.broker.provider.util.SimpleHttp.asResponse(SimpleHttp.java:173)
        at org.keycloak.keycloak-services@7.0.1//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.validateExternalTokenThroughUserInfo(AbstractOAuth2IdentityProvider.java:470)
        at org.keycloak.keycloak-services@7.0.1//org.keycloak.broker.oidc.OIDCIdentityProvider.exchangeExternalImpl(OIDCIdentityProvider.java:706)
        at org.keycloak.keycloak-services@7.0.1//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.exchangeExternal(AbstractOAuth2IdentityProvider.java:519)
        at org.keycloak.keycloak-services@7.0.1//org.keycloak.protocol.oidc.endpoints.TokenEndpoint.exchangeExternalToken(TokenEndpoint.java:951)
        at org.keycloak.keycloak-services@7.0.1//org.keycloak.protocol.oidc.endpoints.TokenEndpoint.tokenExchange(TokenEndpoint.java:730)
        at org.keycloak.keycloak-services@7.0.1//org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:517)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:406)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:370)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:372)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:344)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:137)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:106)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:132)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:100)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.api@1.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.keycloak.keycloak-services@7.0.1//org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:90)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.core@2.0.21.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
        at io.undertow.core@2.0.21.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625)
        ... 102 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
        ... 108 more

17:34:56,548 DEBUG [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-11) Failed to invoke user info status: 0
17:34:56,548 WARN  [org.keycloak.events] (default task-11) type=TOKEN_EXCHANGE_ERROR, realmId=CCBP, clientId=myapp-oidc-login, userId=null, ipAddress=172.20.0.1, error=invalid_token, reason='user info call failure', auth_method=token_exchange, grant_type=urn:ietf:params:oauth:grant-type:token-exchange, subject_issuer=oidc, validation_method='user info', client_auth_method=client-secret
```
SSL Certificate validation failed?
I did turn off validation of certificates, but seemingly it was rederring to different certificates, thus I might set some JVM environment variables for disable verification of SSL certificates

Simply disabling the ssl validation via JVM parameters did not work, som I'm going to try: https://stackoverflow.com/questions/30622599/https-required-while-logging-in-to-keycloak-as-admin


I'm not able to get rid of that exception, disabling ssl validation inside of the pods did not work, in addition to the identity provider settings where I did turn off the validation and turning off ssl on JVM level.

**Comment by tl-luca-baggi** [comment]
That's quite interesting (and quite strange) to be honest, it seems like it doesn't like the SSL certificate carried by ngrok, although if I run `openssl s_client -showcerts -connect <my-ngrok-endpoint>:443` I can see a valid Let's Encrypt cert chain. 

If you're only interested in see token exchange in action you can try with ngrok http url in this way:
1. go to `external_idp` admin console and disable SSL required (`Real Settings > Login > Require SSL`, select the option `none`)
2. Set the `external_idp_endpoint` env variable in the Postman collection and the base URLs in `keycloak` `oidc` identity provider to the ngrok http url (instead of the https one)

**Comment by lucabaggi** [comment]
That's quite interesting (and quite strange) to be honest, it seems like it doesn't like the SSL certificate carried by ngrok, although if I run `openssl s_client -showcerts -connect <my-ngrok-endpoint>:443` I can see a valid Let's Encrypt cert chain. 

If you're only interested in see token exchange in action you can try with ngrok http url in this way:
1. go to `external_idp` admin console and disable SSL required (`Real Settings > Login > Require SSL`, select the option `none`)
2. Set the `external_idp_endpoint` env variable in the Postman collection and the base URLs in `keycloak` `oidc` identity provider to the ngrok http url (instead of the https one)

**Comment by jxsl13** [comment]
The disabling of the Login SSL requirement and the change to http did help a lot.
Thanks you very much!
All I need is a test environment, so this is doing the job pretty fine.

**Comment by lucabaggi** [comment]
@jxsl13 cool, I'm glad you found a way, I'm closing the issue 😉 
If eventually you'll be able to solve also the SSL issue please let me know, thank you!
